__author__ = 'Sacumen(www.sacumen.com)'

"""config module

This modules contains configurations values which controls ss
"""

LEEF_VERSION = "1.0"
VENDOR = "SECURITYSCORECARD IO"
PRODUCT_OVERALL = "SECURITYSCORECARDOVERALL"
PRODUCT_FACTOR = "SECURITYSCORECARDFACTOR"
PRODUCT_ISSUE = "SECURITYSCORECARDISSUE"
PRODUCT_VERSION = "1.0.0"
EVENT_ID_OVERALL = "SECURITYSCORECARDOVERALL"
EVENT_ID_FACTOR = "SECURITYSCORECARDFACTOR"
EVENT_ID_ISSUE = "SECURITYSCORECARDISSUE"

LEEF_HEADER = "LEEF:%s|%s" % (LEEF_VERSION, VENDOR)

DATA_STORE_FILE_PATH = '/store/data.json'

LEEF_FETCH_INTERVAL = 86400

CHECKPOINT_NAME = 'last_run_date'
DAYS = 20
